name: Build and Upload macOS Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Build Script
        shell: bash
        run: |
          mkdir tmp
          cd tmp
          ls /Library/Frameworks
          exit 1
          bash ../build.sh

      - name: Pack FFmpeg Logs
        if: failure()
        run: |
          cd ..
          ls tmp
          mkdir -p logs_out
          tar -czvf logs_out/logs.tar.gz tmp/*.log || echo "No Logs Found"

      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-logs
          path: logs_out/logs.tar.gz